sprint-2/step-2
AndreyKonovalenko/react-burger pull request #4
Opened 2023-04-22 14:01 UTC by AndreyKonovalenko

Добрый день! Направляю на проверку проект на стадии sprint-2/step-2.

Реализовано:
- состояние компонентов перенесено в Redux store;
- перенос ингредиентов в конструктор и сортировка внутри конструктора реализована с помощью библиотеки react-dnd;
- навигация внутри коллекций ингредиентов осуществляется с использованием Intersection Observer API и метода scrollIntoView, для доступа к элементам использован хук useRef.

2023-04-22 15:59 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Использовали `useCallback`
- Хорошая организация хранилища
- `Dnd` работает отлично 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У некоторых компонентов указаны не все пропсы в `propTypes`
- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через thunk
- Вынесите функцию проверки ответа запроса в отдельную функцию - она вам пригодится для всех запросов, которых в будущем станет намного больше

**Можно лучше**
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-22 15:59 UTC, andryxxa93 commented on src/components/app/app.js
> +  const { error, loading } = useSelector((state) => state.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-22 15:59 UTC, andryxxa93 commented on src/components/burger-constructor/burger-element/burger-element.js
> +const BurgerElement = ({ id, ingredient, index }) => {
**Надо исправить**

для этого компонента описаны не все пропсы в PropTypes

2023-04-22 15:59 UTC, andryxxa93 commented on src/services/burger-constructor/burger-constructor-actions.js
> +export const reorder = (dragIndex, hoverIndex) => (dispatch, getState) => {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-04-22 15:59 UTC, andryxxa93 commented on src/utils/burger-api.js
> +  }
**Необходимо исправить**
Вынесите функцию проверки в отдельную функцию - она вам пригодится для всех запросов, которых в будущем станет намного больше

2023-04-22 17:49 UTC, AndreyKonovalenko commented on src/components/app/app.js
> +  const { error, loading } = useSelector((state) => state.ingredients);
Done

2023-04-22 17:50 UTC, AndreyKonovalenko commented on src/components/burger-constructor/burger-element/burger-element.js
> +const BurgerElement = ({ id, ingredient, index }) => {
Dune

2023-04-22 17:50 UTC, AndreyKonovalenko commented on src/services/burger-constructor/burger-constructor-actions.js
> +export const reorder = (dragIndex, hoverIndex) => (dispatch, getState) => {
Dune

2023-04-22 17:51 UTC, AndreyKonovalenko commented on src/utils/burger-api.js
> +  }
Done

2023-04-22 18:07 UTC, AndreyKonovalenko commented on src/services/burger-constructor/burger-constructor-actions.js
> +export const reorder = (dragIndex, hoverIndex) => (dispatch, getState) => {
Исправил замечания.

2023-04-22 18:09 UTC, AndreyKonovalenko commented
Исправил замечаия.

2023-04-23 08:30 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-23 08:56 UTC, merged