sprint-3/step-1
AndreyKonovalenko/react-burger pull request #5
Opened 2023-05-06 19:44 UTC by AndreyKonovalenko

Добрый день! Направляю проект в стадии sprint-3 на проверку.

2023-05-06 20:46 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Показываете ошибку в случае падение запроса
- Настроены все редиректы
- Хорошая организация хранилища для работы с юзером

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если не авторизуясь попытаться попасть на страницу профиля - выдаёт ошибку. Вызывает её пакет - `jwt-decode`

<img width="978" alt="Снимок экрана 2023-05-06 в 23 27 05" src="https://user-images.githubusercontent.com/60173362/236645354-da7af120-7199-4249-88db-245c6c474f8f.png">

- На странице профиля в форме изменения данных не отображается имя
- Не авторизованный юзер не должен иметь возможность сделать заказ
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return `<Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate)`
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло - (jwt-expired), то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
- Для проверки ответа можете создать функцию, которая принимает `url` и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой  `jwt-expired`, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.
- Авторизованную юзеру не должны быть доступны роуты login, register, forgot-password
- Роут `/reset-password` должен быть доступен только через роут `/forgot-password`
- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-06 20:46 UTC, andryxxa93 commented on src/components/protected-route/protected-route.js
> +    const decoded = jwt_decode(token);
**Можно лучше**

способ определения итечения времени жизни токена только по времени нежелателен, т.к. на сервере это время может измениться. Лучше обрабатывать ошибки запросов и при возникновении ошибки jwr expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую
```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-05-06 20:46 UTC, andryxxa93 commented on src/components/app/app.js
> +          <Route path='ingredients/:id' element={<IngredientDetailsPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-07 14:21 UTC, AndreyKonovalenko commented on src/components/protected-route/protected-route.js
> +    const decoded = jwt_decode(token);
Поправил

2023-05-07 14:21 UTC, AndreyKonovalenko commented on src/components/app/app.js
> +          <Route path='ingredients/:id' element={<IngredientDetailsPage />} />
Поправил

2023-05-08 06:59 UTC, andryxxa93 commented
**Необходимо исправить**
 - Авторизованную юзеру не должны быть доступны роуты login, register, forgot-password. В компоненте App вам следует сделать вызов данных юзера - если в хранилище есть токен. Сейчас у вас это происходит только при переходе на страницу профиля. Если сделаете так - уберите в остальных местах этот вызов - чтобы не дублировался.
 - У вас роут `/reset-password` превратился в роут `/forgot-password/reset-password`.  В задании требуется, чтобы роут был доступен только при переходе с роута `/forgot-password`. Менять его название не нужно было.

2023-05-08 15:21 UTC, AndreyKonovalenko commented
Поправил замечания, перенес проверку наличия токенов в app.js.

2023-05-09 08:13 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-09 08:14 UTC, andryxxa93 commented
> Поправил замечания, перенес проверку наличия токенов в app.js.

Можно проверять их наличие внутри самой функции вызова - вам же они нужны при каждом запросе.

2023-05-09 11:16 UTC, merged